<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Alarmino.Installer</RootNamespace>
    <AssemblyName>Alarmino.Installer</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ApplicationIcon>..\..\src\Alarmino\Resources\alarmino.ico</ApplicationIcon>
    <Version>0.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.IO" />
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

</Project>